# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-31 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='Info', max_length=255),
        ),
    ]
